{% set version = "7.2" %}

package:
  name: primecount
  version: {{ version }}

source:
  url: https://github.com/kimwalisch/primecount/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54c1eec33e665a780002dda20cf39ba0cefa8e846fdeda44734fb2265cba9257

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('primecount', max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [unix]
    - ninja        # [win]
    - libgomp      # [linux]
    - llvm-openmp  # [osx and win]
    - clang        # [win]
  host:
    - primesieve

test:
  commands:
    # Check libraries exist
    - test -f "${PREFIX}/include/primecount.h"  # [unix]
    - test -f "${PREFIX}/lib/libprimecount${SHLIB_EXT}"  # [unix]
    - if not exist %PREFIX%\\Library\\include\\primecount.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\primecount.dll exit 1  # [win]

    # Test CLIs.
    - primecount 1e5

about:
  home: https://github.com/kimwalisch/primecount
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast prime counting function implementations

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
