{% set version = "7.8" %}

package:
  name: primecount
  version: {{ version }}

source:
  url: https://github.com/kimwalisch/primecount/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7588b241cd268f4cc6c836135088a143ca65c181278ee0ba3b3309ac055d5ae8

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('primecount', max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [unix]
    - ninja        # [win]
    - libgomp      # [linux]
    - llvm-openmp  # [osx or win]
    - clang        # [win]
  host:
    - primesieve

test:
  commands:
    # Check libraries exist
    - test -f "${PREFIX}/include/primecount.h"  # [unix]
    - test -f "${PREFIX}/lib/libprimecount${SHLIB_EXT}"  # [unix]
    - if not exist %PREFIX%\\Library\\include\\primecount.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\primecount.dll exit 1  # [win]

    # Test CLIs.
    - primecount 1e5

about:
  home: https://github.com/kimwalisch/primecount
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast prime counting function implementations

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
