{% set version = "7.18" %}

package:
  name: primecount
  version: {{ version }}

source:
  url: https://github.com/kimwalisch/primecount/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d8a0127cc4dd9319006b5db6c6f9844532dab9da9c2d410d1e244902463a399

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('primecount', max_pin='x.x') }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [unix]
    - ninja        # [win]
    - libgomp      # [linux]
    - llvm-openmp  # [osx or win]
    - clang        # [win]
  host:
    - primesieve

test:
  commands:
    # Check libraries exist
    - test -f "${PREFIX}/include/primecount.h"  # [unix]
    - test -f "${PREFIX}/lib/libprimecount${SHLIB_EXT}"  # [unix]
    - if not exist %PREFIX%\\Library\\include\\primecount.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\primecount.dll exit 1  # [win]

    # Test CLIs.
    - primecount 1e5

about:
  home: https://github.com/kimwalisch/primecount
  license: BSD-2-Clause
  license_file: COPYING
  summary: Fast prime counting function implementations

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
